import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./component/Navbar";
import Login from "./component/Login";
import Logout from "./component/Logout";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = cookies().get("username");
  return (
    <html lang="en">
      <body className="w-screen h-screen p-24 m-8 flex items-center justify-center">
        {user ? (
          <div className="flex flex-col  items-center justify-center p-24  ">
            <Navbar />
            <Logout />
            <h1>Hi {user.value}</h1>
            {children}
          </div>
        ) : (
          <div className="flex flex-col border border-black items-center justify-center p-24 ">
            Hi Guest <Login />
          </div>
        )}
      </body>
    </html>
  );
}
